#include <string.h>
#include "transport.h"
#include "proto.h"
#include "dsu.h"

/*
 * transport_dcc.c - DCC word-based transport
 *
 * Frame format (all multi-byte values little-endian in word fields):
 *
 *   Request header word (host → CPU, 1 word always):
 *     bit31      : VALID = 1
 *     bits[30:24]: CMD   (same CMD_* as UART, 7 bits)
 *     bits[23:16]: NBYTES (total payload byte count)
 *     bits[15:8] : BYTE0  (first payload byte, 0x00 if none)
 *     bits[7:0]  : BYTE1  (second payload byte, 0x00 if none)
 *
 *   Request data words (if NBYTES > 2), ceil((NBYTES-2)/3) words:
 *     bit31      : VALID = 1
 *     bits[23:16]: BYTE_N
 *     bits[15:8] : BYTE_N+1
 *     bits[7:0]  : BYTE_N+2  (0x00 padding for last word)
 *
 *   Response header word (CPU → host):
 *     bit31      : VALID = 1
 *     bits[30:24]: STATUS (RSP_OK / RSP_ERR_*)
 *     bits[23:16]: NBYTES (response payload byte count)
 *     bits[15:8] : BYTE0
 *     bits[7:0]  : BYTE1
 *
 *   Response data words: same packing as request data words.
 *
 * Commands NOT generated by the DCC transport (handled by SWD):
 *   CMD_ERASE_SLOT, CMD_WRITE_PAGE
 *   These operate on large payloads and are done directly by
 *   OpenOCD flash commands, not through this protocol.
 *
 * All other CMD_* values are fully supported.
 */

/* Pack 3 bytes from buf[offset..] into a DCC data word */
static uint32_t pack_word(const uint8_t *buf, uint16_t offset, uint16_t total)
{
    uint32_t w = 0;
    if (offset     < total) w |= (uint32_t)buf[offset]     << 16;
    if (offset + 1 < total) w |= (uint32_t)buf[offset + 1] <<  8;
    if (offset + 2 < total) w |= (uint32_t)buf[offset + 2];
    return w;
}

/* Unpack 3 bytes from a DCC data word into buf[offset..] */
static void unpack_word(uint32_t w, uint8_t *buf,
                        uint16_t offset, uint16_t total)
{
    if (offset     < total) buf[offset]     = (uint8_t)((w >> 16) & 0xFFU);
    if (offset + 1 < total) buf[offset + 1] = (uint8_t)((w >>  8) & 0xFFU);
    if (offset + 2 < total) buf[offset + 2] = (uint8_t)( w        & 0xFFU);
}

/* ---------------------------------------------------------------
 * transport_dcc.recv
 * --------------------------------------------------------------- */
static uint8_t dcc_recv(uint8_t *buf, uint16_t *out_len)
{
    uint32_t hdr    = dcc_recv_word();
    uint8_t  cmd    = (uint8_t)((hdr >> 24) & 0x7FU);
    uint8_t  nbytes = (uint8_t)((hdr >> 16) & 0xFFU);

    /* First 2 payload bytes are packed in the header word */
    if (nbytes > 0U) buf[0] = (uint8_t)((hdr >> 8) & 0xFFU);
    if (nbytes > 1U) buf[1] = (uint8_t)( hdr        & 0xFFU);

    /* Additional payload words (3 bytes each) */
    uint16_t received = (nbytes > 2U) ? 2U : nbytes;
    while (received < nbytes) {
        uint32_t w = dcc_recv_word();
        unpack_word(w, buf, received, nbytes);
        received += 3U;
    }

    *out_len = nbytes;
    return cmd;
}

/* ---------------------------------------------------------------
 * transport_dcc.send
 * --------------------------------------------------------------- */
static void dcc_send(uint8_t status, const uint8_t *data, uint16_t len)
{
    /* Response header word */
    uint32_t hdr = ((uint32_t)(status & 0x7FU) << 24)
                 | ((uint32_t)(len    & 0xFFU) << 16);
    if (len > 0U && data != NULL) hdr |= (uint32_t)data[0] << 8;
    if (len > 1U && data != NULL) hdr |= (uint32_t)data[1];
    dcc_send_word(hdr);

    /* Additional data words (3 bytes each) */
    if (data == NULL) return;
    uint16_t sent = (len > 2U) ? 2U : len;
    while (sent < len) {
        dcc_send_word(pack_word(data, sent, len));
        sent += 3U;
    }
}

/* ---------------------------------------------------------------
 * Exported instance
 * --------------------------------------------------------------- */
const transport_t transport_dcc = {
    .recv = dcc_recv,
    .send = dcc_send,
};